"""Compatibility Bridge Session 4：RuntimeFigureAsset（ADR 0013）。

四层看护：

* **身份与解析**：`runtime:` id 不透明（脚本名里可以有 `#`）、不含绝对路径；
  解析走注册表正向重算，项目搬移后照样成立（负向反证 #1 的看护对象：
  id 混进绝对路径，move 用例必须红）。
* **materialized cache**：物化产物标记 generated by Tavotto、metadata 最后
  写（负向反证 #5：先写 metadata，原子性用例必须红）、坏 metadata 当没有、
  删掉可重建、清理不破坏文档。
* **stale 判定**：fresh / possibly_stale / missing_source /
  missing_environment / needs_rerun 各有判据；指纹只是提示。
* **产品 API**：probe 即物化；status/preview **绝不执行脚本**（负向反证
  #4：status 顺手 build，这里必须红）；渲染/导出走当次权威 worker（负向
  反证 #2：导出改拿 cache 旧文件，sentinel 用例必须红）；artifact 写回
  后端硬拒绝（负向反证 #3：能力位翻真，工厂派生用例必须红）；未知
  asset source fail closed。

真执行脚本的用例与 test_script_probe.py 同一条纪律：本进程不 import
matplotlib，桌面侧经 pool 起真 worker。
"""

import json
import shutil
from pathlib import Path

import pymupdf
import pytest

from tavotto import app as m
from tavotto.engine import (
    discover,
    figcapture,
    pool as engine_pool,
    project_watch as engine_watch,
    registry as engine_registry,
    runtimeasset,
)

try:
    WORKER_PY = engine_pool.find_worker_python()
except engine_pool.WorkerError:
    WORKER_PY = None

needs_worker = pytest.mark.skipif(
    WORKER_PY is None, reason="找不到装有 matplotlib 的解释器（TAVOTTO_WORKER_PYTHON）"
)

SHOW_ONLY = """\
import matplotlib.pyplot as plt

plt.plot([1, 2, 3], [4, 5, 6])
plt.title("AI generated")
plt.show()
"""


def write(figs: Path, name: str, source: str) -> Path:
    p = figs / name
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(source, encoding="utf-8")
    return p


def _make_project(tmp_path, name="figs"):
    figs = tmp_path / name
    figs.mkdir()
    doc = pymupdf.open()
    doc.new_page(width=100, height=50)
    doc.save(figs / "p1.pdf")
    doc.close()
    return figs


def _registry_of(scripts: dict) -> engine_registry.Registry:
    reg = engine_registry.Registry()
    reg.load_data({"version": 1, "scripts": scripts})
    return reg


def _reg_entry(stems, entry="__main__"):
    return {"entry": entry, "cost": "medium", "notes": "", "stems": list(stems)}


def _descriptor(script="show_only.py", stem="show_only", entry="__main__"):
    """构造一份合法描述符 payload（工厂派生，pyplot 来源、无原件）。"""
    return figcapture.build_descriptor(
        script=script,
        entry=entry,
        stem=stem,
        capture_source=figcapture.SOURCE_PYPLOT,
        execution_profile=figcapture.PROFILE_SAFE,
        size_mm=(120.0, 90.0),
        source_fingerprint="sha256:deadbeef",
    ).to_payload()


@pytest.fixture
def figs(tmp_path):
    d = tmp_path / "figs"
    d.mkdir()
    yield d
    engine_pool.shutdown_all(str(d), wait=True)


@pytest.fixture
def client():
    m.app.config["TESTING"] = True
    m.reset_projects()
    yield m.app.test_client()
    m.reset_projects()
    engine_watch.stop()


# ===========================================================================
# 一、身份与解析（不执行脚本）
# ===========================================================================
class TestIdentityAndResolve:
    def test_is_runtime_id_checks_the_prefix_only(self):
        assert runtimeasset.is_runtime_id("runtime:a.py#x")
        assert not runtimeasset.is_runtime_id("panels/Fig1.pdf")
        assert not runtimeasset.is_runtime_id("")
        assert not runtimeasset.is_runtime_id(None)
        # Windows 盘符不会被误判（绝对路径根本不是面板 id，但也不能撞前缀）
        assert not runtimeasset.is_runtime_id("C:/x/runtime:a.py#x")

    def test_resolve_regenerates_ids_from_the_registry(self):
        reg = _registry_of({"panels/plot.py": _reg_entry(["plot", "plot-2"])})
        got = runtimeasset.resolve("runtime:panels/plot.py#plot-2", reg)
        assert got == {
            "script": "panels/plot.py",
            "stem": "plot-2",
            "entry": "__main__",
            "cost": "medium",
        }
        assert runtimeasset.resolve("runtime:panels/plot.py#nope", reg) is None
        assert runtimeasset.resolve("panels/Fig1.pdf", reg) is None

    def test_resolve_never_parses_the_id(self):
        """脚本名里带 `#`：按 `#` 反解会把 script/stem 劈错——正向重算不会。"""
        reg = _registry_of({"a#b.py": _reg_entry(["x"])})
        asset_id = figcapture.runtime_asset_id("a#b.py", "x")
        got = runtimeasset.resolve(asset_id, reg)
        assert got is not None
        assert got["script"] == "a#b.py" and got["stem"] == "x"

    def test_asset_id_is_project_relative_and_machine_stable(self, tmp_path):
        """同一 (脚本, stem) 在两个不同项目根下 id 完全相同——id 里绝不混入
        绝对路径/机器信息（负向反证 #1 的静态面）。"""
        assert figcapture.runtime_asset_id("panels/p.py", "s") == "runtime:panels/p.py#s"
        with pytest.raises(ValueError):
            figcapture.runtime_asset_id(str(tmp_path / "abs.py"), "s")


# ===========================================================================
# 二、materialized cache（不执行脚本）
# ===========================================================================
class TestCache:
    def test_materialize_marks_generated_by_tavotto(self, figs, tmp_path):
        write(figs, "show_only.py", SHOW_ONLY)
        svg = tmp_path / "preview.svg"
        svg.write_text("<svg>fake preview</svg>", encoding="utf-8")
        desc = _descriptor()
        target = runtimeasset.materialize(figs, desc, svg)
        assert target is not None
        meta = runtimeasset.load_metadata(figs, desc["asset_id"])
        assert meta is not None
        assert meta["generated_by"] == "Tavotto"  # cache 不冒充用户原件
        assert meta["asset_id"] == desc["asset_id"]
        assert meta["descriptor"] == desc
        assert meta["script_sha256"]  # stale 判定的比对基准
        p = runtimeasset.preview_path(figs, desc["asset_id"])
        assert p is not None and p.read_text(encoding="utf-8") == "<svg>fake preview</svg>"

    def test_metadata_is_written_last(self, figs, tmp_path, monkeypatch):
        """预览写失败 → 磁盘上**不能**留下 metadata（负向反证 #5 的看护对象：
        先写 metadata 再写预览，这里必须红）。"""
        write(figs, "show_only.py", SHOW_ONLY)
        svg = tmp_path / "preview.svg"
        svg.write_text("<svg/>", encoding="utf-8")
        desc = _descriptor()

        real_replace = runtimeasset.os.replace

        def failing_replace(src, dst):
            if str(dst).endswith("preview.svg"):
                raise OSError("disk full")
            return real_replace(src, dst)

        monkeypatch.setattr(runtimeasset.os, "replace", failing_replace)
        assert runtimeasset.materialize(figs, desc, svg) is None
        monkeypatch.undo()
        assert not (runtimeasset.cache_dir(figs, desc["asset_id"]) / "metadata.json").exists()
        assert runtimeasset.load_metadata(figs, desc["asset_id"]) is None

    def test_broken_metadata_is_treated_as_absent(self, figs, tmp_path):
        write(figs, "show_only.py", SHOW_ONLY)
        svg = tmp_path / "p.svg"
        svg.write_text("<svg/>", encoding="utf-8")
        desc = _descriptor()
        runtimeasset.materialize(figs, desc, svg)
        target = runtimeasset.cache_dir(figs, desc["asset_id"])

        (target / "metadata.json").write_text("{ not json", encoding="utf-8")
        assert runtimeasset.load_metadata(figs, desc["asset_id"]) is None

        meta = {
            "schema": runtimeasset.CACHE_SCHEMA,
            "generated_by": "Tavotto",
            "asset_id": "runtime:other.py#x",
            "preview": "preview.svg",
        }
        (target / "metadata.json").write_text(json.dumps(meta), encoding="utf-8")
        assert runtimeasset.load_metadata(figs, desc["asset_id"]) is None

        meta["asset_id"] = desc["asset_id"]
        meta["preview"] = "not_there.svg"
        (target / "metadata.json").write_text(json.dumps(meta), encoding="utf-8")
        assert runtimeasset.load_metadata(figs, desc["asset_id"]) is None

    def test_cache_can_be_deleted_and_pruned(self, figs, tmp_path):
        write(figs, "show_only.py", SHOW_ONLY)
        svg = tmp_path / "p.svg"
        svg.write_text("<svg/>", encoding="utf-8")
        desc = _descriptor()
        runtimeasset.materialize(figs, desc, svg)
        assert runtimeasset.load_metadata(figs, desc["asset_id"]) is not None

        runtimeasset.drop_cache(figs, desc["asset_id"])
        assert runtimeasset.load_metadata(figs, desc["asset_id"]) is None

        runtimeasset.materialize(figs, desc, svg)  # 可重建
        assert runtimeasset.load_metadata(figs, desc["asset_id"]) is not None
        removed = runtimeasset.prune_cache(max_bytes=0, keep=0)
        assert removed >= 1
        assert runtimeasset.load_metadata(figs, desc["asset_id"]) is None


# ===========================================================================
# 三、stale 判定（不执行脚本；worker_python 注入）
# ===========================================================================
class TestStaleStatus:
    def _materialized(self, figs, tmp_path):
        write(figs, "show_only.py", SHOW_ONLY)
        svg = tmp_path / "p.svg"
        svg.write_text("<svg/>", encoding="utf-8")
        desc = _descriptor()
        runtimeasset.materialize(figs, desc, svg)
        reg = _registry_of({"show_only.py": _reg_entry(["show_only"])})
        return desc["asset_id"], reg

    def test_fresh_when_nothing_changed(self, figs, tmp_path):
        asset_id, reg = self._materialized(figs, tmp_path)
        st = runtimeasset.stale_status(figs, asset_id, reg, worker_python="python3")
        assert st["status"] == runtimeasset.STALE_FRESH
        assert st["registered"] is True and st["cached"] is True

    def test_possibly_stale_after_script_edit(self, figs, tmp_path):
        asset_id, reg = self._materialized(figs, tmp_path)
        write(figs, "show_only.py", SHOW_ONLY + "\n# edited\n")
        st = runtimeasset.stale_status(figs, asset_id, reg, worker_python="python3")
        assert st["status"] == runtimeasset.STALE_POSSIBLY

    def test_possibly_stale_after_entry_change(self, figs, tmp_path):
        asset_id, _ = self._materialized(figs, tmp_path)
        reg = _registry_of({"show_only.py": _reg_entry(["show_only"], entry="main")})
        st = runtimeasset.stale_status(figs, asset_id, reg, worker_python="python3")
        assert st["status"] == runtimeasset.STALE_POSSIBLY

    def test_missing_source_when_the_script_is_gone(self, figs, tmp_path):
        asset_id, reg = self._materialized(figs, tmp_path)
        (figs / "show_only.py").unlink()
        st = runtimeasset.stale_status(figs, asset_id, reg, worker_python="python3")
        assert st["status"] == runtimeasset.STALE_MISSING_SOURCE

    def test_missing_environment(self, figs, tmp_path):
        asset_id, reg = self._materialized(figs, tmp_path)

        def no_python():
            raise RuntimeError("no interpreter anywhere")

        st = runtimeasset.stale_status(figs, asset_id, reg, worker_python=no_python)
        assert st["status"] == runtimeasset.STALE_MISSING_ENVIRONMENT
        st = runtimeasset.stale_status(figs, asset_id, reg, worker_python=None)
        assert st["status"] == runtimeasset.STALE_MISSING_ENVIRONMENT

    def test_needs_rerun_without_cache(self, figs):
        write(figs, "show_only.py", SHOW_ONLY)
        reg = _registry_of({"show_only.py": _reg_entry(["show_only"])})
        st = runtimeasset.stale_status(
            figs, "runtime:show_only.py#show_only", reg, worker_python="python3"
        )
        assert st["status"] == runtimeasset.STALE_NEEDS_RERUN
        assert st["cached"] is False

    def test_unregistered_with_matching_source_block_needs_rerun(self, figs):
        """注册表条目没了，但文档描述块与 id 对得上：可恢复（needs_rerun），
        不丢文档。"""
        write(figs, "show_only.py", SHOW_ONLY)
        reg = _registry_of({})
        st = runtimeasset.stale_status(
            figs,
            "runtime:show_only.py#show_only",
            reg,
            source={"script": "show_only.py", "stem": "show_only"},
            worker_python="python3",
        )
        assert st["status"] == runtimeasset.STALE_NEEDS_RERUN
        assert st["registered"] is False

    def test_source_block_mismatch_fails_closed(self, figs):
        """描述块重算出的 id 与请求的对不上 → 未知，绝不套到猜出来的脚本上。"""
        write(figs, "other.py", SHOW_ONLY)
        reg = _registry_of({})
        st = runtimeasset.stale_status(
            figs,
            "runtime:show_only.py#show_only",
            reg,
            source={"script": "other.py", "stem": "other"},
            worker_python="python3",
        )
        assert st["status"] is None


# ===========================================================================
# 四、writeback 裁决与错误码纪律
# ===========================================================================
class TestWritebackContract:
    def test_v1_rejects_both_writeback_kinds(self):
        assert (
            runtimeasset.writeback_rejection("artifact") == "runtime_asset_has_no_original_artifact"
        )
        assert runtimeasset.writeback_rejection("source") == "runtime_source_writeback_unsupported"

    def test_app_layer_literals_match_the_engine_authority(self):
        """app.py 的字面量 code 是 runtimeasset.ERROR_* 的镜像（字面量是
        test_error_codes 结构扫描的要求，这里对拍两侧不漂移）。"""
        src = (Path(m.__file__)).read_text(encoding="utf-8")
        assert f'"code": "{runtimeasset.ERROR_NO_ARTIFACT}"' in src
        assert f'"code": "{runtimeasset.ERROR_UNKNOWN}"' in src
        assert f'"code": "{runtimeasset.ERROR_CACHE_MISSING}"' in src

    def test_runtime_error_codes_have_text_in_both_languages(self):
        """码表 ←→ 双语文案对拍（probe 码表纪律的延伸）。
        runtime_source_writeback_unsupported 尚无 producer 端点，也必须先有
        文案——「新码先加表、加文案、加对拍，再有 producer」。"""
        locales = Path(__file__).resolve().parent.parent / "web" / "src" / "i18n" / "locales"
        if not (locales / "zh-CN" / "errors.json").is_file():
            pytest.skip("没有 web/（wheel/sdist 里不含前端源码）")
        codes = (
            runtimeasset.ERROR_UNKNOWN,
            runtimeasset.ERROR_NO_ARTIFACT,
            runtimeasset.ERROR_SOURCE_WRITEBACK,
            runtimeasset.ERROR_CACHE_MISSING,
        )
        for locale in ("zh-CN", "en-US"):
            table = json.loads((locales / locale / "errors.json").read_text(encoding="utf-8"))[
                "backend"
            ]
            for code in codes:
                assert code in table and str(table[code]).strip(), f"{locale} 缺 {code} 的文案"

    def test_descriptor_capabilities_are_derived_not_declared(self):
        """负向反证 #3 的看护对象：把 can_writeback_artifact 硬设 true，
        这里（与 figcapture 工厂）必须红。"""
        desc = _descriptor()
        assert desc["can_writeback_artifact"] is False
        assert desc["can_writeback_source"] is False
        with pytest.raises(ValueError):
            figcapture.descriptor_from_payload({**desc, "can_writeback_artifact": True})


# ===========================================================================
# 五、产品 API：完整链路（真 worker）
# ===========================================================================
@needs_worker
class TestRuntimeProductApi:
    def _probe(self, client, figs, script="show_only.py"):
        client.post("/api/projects/open", json={"path": str(figs)})
        resp = client.post("/api/registry/probe", json={"script": script})
        assert resp.status_code == 200
        result = resp.get_json()
        assert result["error"] is None and result["registered"] is True
        return result

    def test_probe_materializes_and_the_full_chain_holds(self, client, tmp_path):
        """probe → 物化 → status fresh → preview 可取 → 渲染（热会话）→
        manifest 到手。一次执行贯穿全链（execution-count 纪律）。"""
        figs = _make_project(tmp_path)
        counter = tmp_path / "count.txt"
        write(
            figs,
            "counted.py",
            "from pathlib import Path\n"
            "import matplotlib.pyplot as plt\n"
            "def main():\n"
            f"    p = Path({str(counter)!r})\n"
            "    n = int(p.read_text()) if p.exists() else 0\n"
            "    p.write_text(str(n + 1))\n"
            "    plt.plot([1, 2, 3])\n",
        )
        try:
            result = self._probe(client, figs, "counted.py")
            (d,) = result["descriptors"]
            asset_id = d["asset_id"]
            assert asset_id == "runtime:counted.py#counted"

            # probe 当场物化：preview 立即可取（不再执行）
            meta = runtimeasset.load_metadata(figs, asset_id)
            assert meta is not None and meta["generated_by"] == "Tavotto"
            resp = client.get("/api/runtime/preview", query_string={"id": asset_id})
            assert resp.status_code == 200
            assert b"<svg" in resp.data.lower()

            st = client.post("/api/runtime/status", json={"id": asset_id}).get_json()
            assert st["status"] == runtimeasset.STALE_FRESH
            assert st["cached"] is True and st["registered"] is True

            # 渲染复用热会话：manifest 到手，执行计数仍是 1
            r = client.post(
                "/api/engine/render", json={"id": asset_id, "patches": [], "inline_svg": True}
            )
            assert r.status_code == 200
            body = r.get_json()
            assert body["manifest"]["elements"]
            assert "svg" in body
            assert int(counter.read_text()) == 1
        finally:
            engine_pool.shutdown_all(str(figs), wait=True)

    def test_multi_figure_assets_are_distinct(self, client, tmp_path):
        figs = _make_project(tmp_path)
        write(
            figs,
            "multi.py",
            "import matplotlib.pyplot as plt\n"
            "for i in range(2):\n"
            "    plt.figure(figsize=(3, 2))\n"
            "    plt.plot([1, 2, i])\n"
            "plt.show()\n",
        )
        try:
            result = self._probe(client, figs, "multi.py")
            ids = [d["asset_id"] for d in result["descriptors"]]
            assert ids == ["runtime:multi.py#multi", "runtime:multi.py#multi-2"]
            assert len(set(ids)) == 2
            for asset_id in ids:
                st = client.post("/api/runtime/status", json={"id": asset_id}).get_json()
                assert st["status"] == runtimeasset.STALE_FRESH
                r = client.post("/api/engine/render", json={"id": asset_id, "patches": []})
                assert r.status_code == 200
        finally:
            engine_pool.shutdown_all(str(figs), wait=True)

    def test_status_and_preview_never_execute_the_script(self, client, tmp_path):
        """负向反证 #4 的看护对象：打开项目 + status + preview 全程零执行
        （status 顺手 build 的话，这里必须红）。"""
        figs = _make_project(tmp_path)
        write(figs, "show_only.py", SHOW_ONLY)
        # 手工登记（不 probe）：模拟「重开项目」——注册表在、cache 不在
        discover.register(figs, "show_only.py", ["show_only"], entry="__main__")
        client.post("/api/projects/open", json={"path": str(figs)})
        asset_id = "runtime:show_only.py#show_only"

        st = client.post("/api/runtime/status", json={"id": asset_id}).get_json()
        assert st["status"] == runtimeasset.STALE_NEEDS_RERUN
        resp = client.get("/api/runtime/preview", query_string={"id": asset_id})
        assert resp.status_code == 404
        assert resp.get_json()["code"] == "runtime_cache_missing"
        # 全程没有为这份脚本 spawn 过 worker
        key = (engine_pool._norm_dir(str(figs)), "show_only.py")
        assert key not in engine_pool._workers

    def test_lazy_render_rebuilds_the_cache(self, client, tmp_path):
        """删掉 cache → 首次渲染 lazy build → cache 原地重建（保存/重开的
        恢复路径）。"""
        figs = _make_project(tmp_path)
        write(figs, "show_only.py", SHOW_ONLY)
        try:
            result = self._probe(client, figs)
            (d,) = result["descriptors"]
            asset_id = d["asset_id"]
            engine_pool.shutdown_all(str(figs), wait=True)  # 模拟重开 app
            runtimeasset.drop_cache(figs, asset_id)
            assert (
                client.get("/api/runtime/preview", query_string={"id": asset_id}).status_code == 404
            )

            r = client.post(
                "/api/engine/render", json={"id": asset_id, "patches": [], "inline_svg": True}
            )
            assert r.status_code == 200
            assert (
                client.get("/api/runtime/preview", query_string={"id": asset_id}).status_code == 200
            )
        finally:
            engine_pool.shutdown_all(str(figs), wait=True)

    def test_override_replay_survives_reopen(self, client, tmp_path):
        """重开（新 worker）后按文档里的 overrides 重放：同一 gid 仍在
        manifest 里、渲染成功——override 不丢、不挂错对象。"""
        figs = _make_project(tmp_path)
        write(figs, "show_only.py", SHOW_ONLY)
        try:
            self._probe(client, figs)
            asset_id = "runtime:show_only.py#show_only"
            r = client.post("/api/engine/render", json={"id": asset_id, "patches": []}).get_json()
            title_gid = next(
                el["gid"]
                for el in r["manifest"]["elements"]
                if any(
                    f.get("prop") == "text" and f.get("type") == "text"
                    for f in el.get("editable", [])
                )
            )

            engine_pool.shutdown_all(str(figs), wait=True)  # 模拟重开
            patches = [{"gid": title_gid, "prop": "text", "value": "Replayed"}]
            r2 = client.post("/api/engine/render", json={"id": asset_id, "patches": patches})
            assert r2.status_code == 200
            body = r2.get_json()
            assert body["warnings"] == []
            assert any(el["gid"] == title_gid for el in body["manifest"]["elements"])
        finally:
            engine_pool.shutdown_all(str(figs), wait=True)

    def test_project_move_keeps_the_identity(self, client, tmp_path):
        """整个项目换目录：asset id 不变、注册表随图库走、渲染照常
        （负向反证 #1 的看护对象：id 里混进绝对路径，这里必须红）。"""
        figs = _make_project(tmp_path, "old_home")
        write(figs, "show_only.py", SHOW_ONLY)
        try:
            result = self._probe(client, figs)
            asset_id = result["descriptors"][0]["asset_id"]
        finally:
            engine_pool.shutdown_all(str(figs), wait=True)
        m.reset_projects()

        moved = tmp_path / "new_home"
        shutil.move(str(figs), str(moved))
        try:
            client.post("/api/projects/open", json={"path": str(moved)})
            st = client.post("/api/runtime/status", json={"id": asset_id}).get_json()
            # 新位置没有 cache（cache 键含项目路径），但身份与登记原样成立
            assert st["registered"] is True
            assert st["script"] == "show_only.py"
            assert st["status"] == runtimeasset.STALE_NEEDS_RERUN
            r = client.post("/api/engine/render", json={"id": asset_id, "patches": []})
            assert r.status_code == 200
            # 渲染顺手把新位置的 cache 物化出来
            assert (
                client.get("/api/runtime/preview", query_string={"id": asset_id}).status_code == 200
            )
        finally:
            engine_pool.shutdown_all(str(moved), wait=True)

    def test_export_uses_the_live_worker_not_the_cache(self, client, tmp_path):
        """负向反证 #2 的看护对象：把 cache 预览换成哨兵垃圾，导出必须仍
        成功且产物是 worker 现渲染的 PDF——导出改拿 cache 文件的话这里红。"""
        figs = _make_project(tmp_path)
        write(figs, "show_only.py", SHOW_ONLY)
        try:
            self._probe(client, figs)
            asset_id = "runtime:show_only.py#show_only"
            # 哨兵：cache 里躺着一份根本不是图的垃圾
            target = runtimeasset.cache_dir(figs, asset_id)
            (target / "preview.svg").write_text("SENTINEL-NOT-A-FIGURE", encoding="utf-8")
            spec = {
                "page_w_mm": 150,
                "page_h_mm": 100,
                "dpi": 150,
                "formats": ["pdf"],
                "stem": "runtime_export",
                "objects": [
                    {
                        "type": "panel",
                        "id": asset_id,
                        "x_mm": 10,
                        "y_mm": 10,
                        "w_mm": 100,
                        "h_mm": 75,
                        "overrides": [],
                    }
                ],
            }
            r = client.post("/api/export", json=spec)
            assert r.status_code == 200
            (f,) = r.get_json()["files"]
            out = Path(r.get_json()["export_dir"]) / f["name"]
            doc = pymupdf.open(out)
            try:
                assert doc.page_count == 1
                # 页面上有真实矢量内容（哨兵字符串画不出 drawings）
                assert doc[0].get_drawings()
                assert b"SENTINEL-NOT-A-FIGURE" not in out.read_bytes()
            finally:
                doc.close()
        finally:
            engine_pool.shutdown_all(str(figs), wait=True)

    def test_artifact_writeback_is_hard_rejected(self, client, tmp_path):
        """后端硬拒绝，不是藏按钮：update_source 与 history/restore 对
        runtime id 一律 400 + 稳定 code。"""
        figs = _make_project(tmp_path)
        write(figs, "show_only.py", SHOW_ONLY)
        try:
            self._probe(client, figs)
            asset_id = "runtime:show_only.py#show_only"
            r = client.post("/api/engine/update_source", json={"id": asset_id, "patches": []})
            assert r.status_code == 400
            assert r.get_json()["code"] == "runtime_asset_has_no_original_artifact"
            r = client.post("/api/engine/history/restore", json={"id": asset_id, "n": -1})
            assert r.status_code == 400
            assert r.get_json()["code"] == "runtime_asset_has_no_original_artifact"
        finally:
            engine_pool.shutdown_all(str(figs), wait=True)

    def test_unknown_asset_sources_fail_closed(self, client, tmp_path):
        """未知 fileId 形态绝不猜成文件：runtime 前缀但未登记 → 404 稳定
        code；来历不明的其它前缀 → 404（safe_resolve 的文件判据挡住），
        绝不落到「当成相对路径读出别的文件」。"""
        figs = _make_project(tmp_path)
        client.post("/api/projects/open", json={"path": str(figs)})
        r = client.post("/api/engine/render", json={"id": "runtime:ghost.py#ghost", "patches": []})
        assert r.status_code == 404
        assert r.get_json()["code"] == "runtime_asset_unknown"
        r = client.post("/api/engine/render", json={"id": "future:whatever", "patches": []})
        assert r.status_code == 404
        st = client.post("/api/runtime/status", json={"id": "p1.pdf"})
        assert st.status_code == 400
        assert st.get_json()["code"] == "runtime_asset_unknown"

    def test_package_carries_the_script_not_the_cache(self, client, tmp_path):
        """项目包（决策：只带描述符 + 脚本）：runtime 面板不算 missing，
        脚本进包，cache 一个字节不进包。"""
        figs = _make_project(tmp_path)
        write(figs, "show_only.py", SHOW_ONLY)
        try:
            self._probe(client, figs)
            asset_id = "runtime:show_only.py#show_only"
            doc = {
                "schema": 2,
                "name": "t",
                "page": {"w": 150, "h": 100},
                "objects": [
                    {
                        "type": "panel",
                        "id": "obj1",
                        "fileId": asset_id,
                        "fileKind": "runtime",
                        "overrides": [],
                    }
                ],
                "guides": [],
            }
            r = client.post("/api/package", json={"doc": doc, "stem": "pkg"})
            assert r.status_code == 200
            body = r.get_json()
            assert body["missing"] == []
            import zipfile

            export_dir = None
            for base in (figs / "tavottofile" / "export",):
                if base.is_dir():
                    export_dir = base
            assert export_dir is not None
            (pkg,) = sorted(export_dir.glob("pkg_*"))
            with zipfile.ZipFile(pkg) as z:
                names = z.namelist()
                manifest = json.loads(z.read("package_manifest.json"))
            assert "scripts/show_only.py" in names
            assert not any("cache" in n or "preview" in n for n in names)
            (ra,) = manifest["runtime_assets"]
            assert ra["id"] == asset_id and ra["script"] == "show_only.py"
            assert asset_id not in manifest["missing_at_pack_time"]
        finally:
            engine_pool.shutdown_all(str(figs), wait=True)

    def test_status_says_which_profile_produced_this_figure(self, client, tmp_path):
        """`/api/runtime/status` 带上 `execution_profile`（ADR 0021 §9.4）。

        这是**离线角标**的数据源。native 会话结束之后 cache 里仍然有一张
        预览，但对象级编辑与权威导出都不可用了；界面靠这个字段在**重开文档
        那一刻**就说得出来，而不是等用户点进图内编辑撞上一条 409。

        两个方向都量：真跑出来的 safe 图报 `safe`，把 cache 里的描述符改成
        native 之后报 `native`。只量后者的话，一个「无脑回 native」的实现
        照样绿——而那会给每一个普通 runtime 面板都挂上「会话已结束」。
        """
        figs = _make_project(tmp_path)
        write(figs, "show_only.py", SHOW_ONLY)
        try:
            (d,) = self._probe(client, figs, "show_only.py")["descriptors"]
            asset_id = d["asset_id"]

            st = client.post("/api/runtime/status", json={"id": asset_id}).get_json()
            assert st["execution_profile"] == "safe", st

            # 把物化下来的那份描述符改成 native——这正是一条 native 会话
            # 跑完之后 cache 里的样子（`_materialize_native` 写的就是它）
            meta_path = runtimeasset.cache_dir(figs, asset_id) / "metadata.json"
            meta = json.loads(meta_path.read_text(encoding="utf-8"))
            meta["descriptor"]["execution_profile"] = "native"
            meta_path.write_text(json.dumps(meta, ensure_ascii=False), encoding="utf-8")

            st = client.post("/api/runtime/status", json={"id": asset_id}).get_json()
            assert st["execution_profile"] == "native", st
        finally:
            engine_pool.shutdown_all(str(figs), wait=True)
